language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install: "pip install -r requirements.txt"

script: echo 'Temp test'

jobs:
  include:
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
